from django.conf.urls.static import static
from django.urls import path
from django.conf import settings
from.import views

urlpatterns = [
  path('',views.index,name=""),
  path('index/',views.index,name="index"),
  path('login',views.login,name="login"),
  path('about',views.about,name="about"),
  path('contact',views.contact,name="contact"),
  path('courses',views.courses,name="courses"),
  path('teacher',views.teacher,name="teacher"),
  path('adminhome/',views.adminhome,name="adminhome"),
  path('privacy',views.privacy,name="privacy"),
  path('logout',views.logout,name="logout"),
  path('adminhead',views.adminhead,name="adminhead"),
  path('addcollege/',views.addcollege,name="addcollege"),
  path('college',views.college,name="college"),
  path('collegelist/',views.collegelist,name="collegelist"),
  path('addcourse/',views.addcourse,name="addcourse"),
  path('course',views.course,name="course"),
  path('courselist',views.courselist,name="courselist"),
  path('viewmail',views.viewmail,name="viewmail"),
  path('userhome/',views.userhome,name="userhome"),
  path('change',views.change,name="change"),
  path('reg',views.reg,name="reg"),
  path('userchange',views.userchange,name="userchange"),
  path('colleges',views.colleges,name="colleges"),
  path('usrcourse',views.usrcourse,name="usrcourse"),
  path('mail/',views.mail,name="mail"),
  path('deletecollege',views.deletecollege,name="deletecollege"),
  path('editcollege',views.editcollege,name="editcollege"),
  path('email',views.email,name="email"),
  path('deletecourse',views.deletecourse,name="deletecourse"),
  path('editcourse',views.editcourse,name="editcourse"),
  path('profile/',views.profile,name="profile"),
  path('addfee/',views.addfee,name="addfee"),
  path('fee',views.fee,name="fee"),
  path('feelist/',views.feelist,name="feelist"),
  path('editfee',views.editfee,name="editfee"),
  path('deletefee',views.deletefee,name="deletefee"),
  path('apply/',views.apply,name="apply"),
  path('app/',views.app,name="app"),
  path('getcor/',views.getcor,name="getcor"),
  path('application/',views.application,name="application"),
  path('admission',views.admission,name="admission"),
  path('students/',views.students,name="students"),
  path('deleteuser',views.deleteuser,name="deleteuser"),
  path('addprospectus/',views.addprospectus,name="addprospectus"),
  path('prospectus',views.prospectus,name="prospectus"),
  path('prospectuslist/',views.prospectuslist,name="prospectuslist"),
  path('deleteprospectus',views.deleteprospectus,name="deleteprospectus"),
  path('downpros/',views.downpros,name="downpros"),
  path('editprofile',views.editprofile,name="editprofile"),
  path('approvereg',views.approvereg,name="approvereg"),
  path('rejectreg',views.rejectreg,name="rejectreg"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)